<div class="blog">
    <h1>Our Story</h1>
    <img src="http://sneezyt.files.wordpress.com/2013/12/20131216-191027.jpg" class="inline-img" />
    <p>
        Sneezy T was diagnosed with an incurable disease called Eosinophilic Esophagitis (EoE) at 15 months old. At the time of his diagnosis, he was already off the top 8 food allergens and sesame seeds, taking a proton-pump inhibitor, vomiting 3-5 times a day and losing weight rapidly. His endoscopy showed that he had major inflammation, exudite, and scar tissue rings forming inside his esophagus. In addition, the biopsy indicated that he had 75 eosinophils present in his lower esophagus. A normal esophagus has zero.
    </p>
    <p>
        The doctor told us that we needed to go back for more allergy testing because something currently in his diet was triggering eosinophils to attack his esophagus. We did do some more allergy testing and removed corn and beef from his diet. Although that helped slow the vomiting to once or twice a day, it didn’t stop it.  We had been keeping a food diary and symptoms written down, but we just couldn’t pinpoint what was causing the problem.
    </p>
    <p>
        I remember staring at our pages and pages of notes crying and wondering why something so basic as food could make my son so sick. It was heartbreaking. It seemed he couldn’t keep anything down and we were told we were headed down a path to a feeding tube, if we couldn’t get him healthy.
    </p>
    <p>
        At that time, we took his health into our own hands because after all the testing, no one or no medical test could tell us what was making him so sick. We started creating a digital database of his symptoms, foods consumed, treatments, and pollens to see if we could find the missing puzzle piece. After creating a basic structure for the program, he spent every night after work entering data from the previous three months.
    </p>
    <p>
        At first, it was more of a data gathering exercise.   Input this food, these environmental allergies, these medicines, and track the reactions.   After a few weeks, we started to see if anything correlated.   Charles arranged a view where we got to look at what foods does he seem to react to the most.   Instantly, something jumped out.   90% of the time, Sneezy T vomited within two hours of eating coconuts!    Unlike egg or milk where the reaction was immediate, he was having a delayed reaction to this nut!    Coconut is also what everyone recommended to take when trying to add weight and use as a milk substitute.  This new view of the data highlighted this reaction.   By removing coconut and tracking some other less obvious reactions, the vomiting was reduced.   By December, when Sneezy T got his next scope for EoE, he was in full remission.   He will not always be in remission but our family is better off because of this software.
    </p>
    <p>
        There is no promise or guarantee that others will have the same fortune by using this application.  However, it helped us to the point that we wanted to share it with others.
    </p>
    <p>
        If you like this application, a recipe, or some comic relief that you've received as a result of our efforts, please donate money to our paypal account to help us keep up the administrative fees associated with hosting this site. Half of all the donations to our paypal account will be sent to the <a href="http://apfed.org/drupal/drupal/index.php">American Partnership for Eosinophilic Disorders (APFED)</a> in the hopes that we will find a cure for those suffering with Eosinophilic Disorders.
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHNwYJKoZIhvcNAQcEoIIHKDCCByQCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYCGYX5EuB4Pum9DLLEbUKL2UFLJ/nRbFExachDOniUIlOVzzi883ju6vCqFH4In/3YbuoIS8wy1NchEU38KTANN2N8MqAjDNTywmTdPdmbvb7EDwx0Y3a4IdOOSPsc5aGof4+MSg5gyGa4bsPWQxzAxUO2uIxmR7UvchaQ3MeN9RDELMAkGBSsOAwIaBQAwgbQGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIziGn3CDJ77iAgZCxLqKDneExptqg5LMpu7XyWpovuiJPdPYDJkAeUCjajMQhAodYvBAVcxPdwxn7NcnzkOqb4X9tN7D7DEVcUA6gAqYT1bmKksFq2QmE+Zih6Y+EJVnw7Ec9uWCY7xlRms6kNHCRLrEYO+QDmC3Uw5udqpnHbNo7rStkfEvNr/5OSFlsGo5xauLMSavC7NSPUy6gggOHMIIDgzCCAuygAwIBAgIBADANBgkqhkiG9w0BAQUFADCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wHhcNMDQwMjEzMTAxMzE1WhcNMzUwMjEzMTAxMzE1WjCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMFHTt38RMxLXJyO2SmS+Ndl72T7oKJ4u4uw+6awntALWh03PewmIJuzbALScsTS4sZoS1fKciBGoh11gIfHzylvkdNe/hJl66/RGqrj5rFb08sAABNTzDTiqqNpJeBsYs/c2aiGozptX2RlnBktH+SUNpAajW724Nv2Wvhif6sFAgMBAAGjge4wgeswHQYDVR0OBBYEFJaffLvGbxe9WT9S1wob7BDWZJRrMIG7BgNVHSMEgbMwgbCAFJaffLvGbxe9WT9S1wob7BDWZJRroYGUpIGRMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbYIBADAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAIFfOlaagFrl71+jq6OKidbWFSE+Q4FqROvdgIONth+8kSK//Y/4ihuE4Ymvzn5ceE3S/iBSQQMjyvb+s2TWbQYDwcp129OPIbD9epdr4tJOUNiSojw7BHwYRiPh58S1xGlFgHFXwrEBb3dgNbMUa+u4qectsMAXpVHnD9wIyfmHMYIBmjCCAZYCAQEwgZQwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tAgEAMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xNDAyMTUwNDI3MzRaMCMGCSqGSIb3DQEJBDEWBBQW/bl5J+L+jQtc+nLqlafQ0Uhg3zANBgkqhkiG9w0BAQEFAASBgHm0h34o/MqTPmq53HUhelA435Zeqowc97e9ncOi59/10qU8PN94896eyEKiNRYLfSDgC48zVsJ8jXi5ersF1shx9eY00we1iraNz7mBeKnRUoHPc4Xu0rf7ZUOxnFQTNPBEsdP2s1u5LEkrSvbvwgmMLm/ECHqL3gTvZinbUYZQ-----END PKCS7-----">
        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
        <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>
    </p>
    <p>
        You can read more about our adventures with EoE and find common recipes at the <a href="http://sneezyt.wordpress.com">Sneezy T Blog</a>
    </p>
</div>